### ISSUE TITLE
todo/drop-old-feature-branches

### ISSUE THREAD

**Issue by fkoh111** [bath-se2-group3/NewBank#13]
Can we drop the old feature branches?

@saundap:  
- [X] [5-addition-new-customer](https://github.com/bath-se2-group3/NewBank/tree/5-addition-new-customer)  

@DaMurdoc:  
- [ ] [enable-pay-rebased-branch](https://github.com/bath-se2-group3/NewBank/tree/enable-pay-rebased-branch)  
- [ ] [pay-enable-payment](https://github.com/bath-se2-group3/NewBank/tree/pay-enable-payment)
